global using System.Reflection;
global using FluentValidation;
global using Microsoft.Extensions.DependencyInjection;
global using MediatR;
global using MediLogix.Application.DTOs;
global using MediLogix.Application.Queries.Device;
global using MediLogix.Infrastructure.Persistence.Database;
global using Microsoft.EntityFrameworkCore;
global using MediLogix.Domain.Entities;
